In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
#path to csv
file= "NFL_results.csv"

#read data into pandas
NFL_df = pd.read_csv(file)
NFL_df.head(10)

,season,Week,Day,Date,Var.5,Winner/tie,Var.7,Loser/tie,PtsW,PtsL,YdsW,TOW,YdsL,TOL
0,1960,1,Fri,September 23,boxscore,St. Louis Cardinals,@,Los Angeles Rams,43.0,21.0,430.0,5.0,238.0,6.0
1,1960,1,Sat,September 24,boxscore,Pittsburgh Steelers,@,Dallas Cowboys,35.0,28.0,475.0,1.0,395.0,4.0
2,1960,1,Sun,September 25,boxscore,Chicago Bears,@,Green Bay Packers,17.0,14.0,306.0,4.0,230.0,3.0
3,1960,1,Sun,September 25,boxscore,Baltimore Colts,NaN,Washington Redskins,20.0,0.0,344.0,1.0,113.0,3.0
4,1960,1,Sun,September 25,boxscore,New York Giants,@,San Francisco 49ers,21.0,19.0,278.0,2.0,335.0,1.0
5,1960,1,Sun,September 25,boxscore,Cleveland Browns,@,Philadelphia Eagles,41.0,24.0,396.0,0.0,406.0,4.0
6,1960,2,Fri,September 30,boxscore,Philadelphia Eagles,@,Dallas Cowboys,27.0,25.0,301.0,5.0,339.0,5.0
7,1960,2,Sun,October 2,boxscore,Green Bay Packers,NaN,Detroit Lions,28.0,9.0,364.0,3.0,272.0,1.0
8,1960,2,Sun,October 2,boxscore,San Francisco 49ers,NaN,Los Angeles Rams,13.0,9.0,284.0,1.0,199.0,1.0
9,1960,2,Sun,October 2,boxscore,Cleveland Browns,NaN,Pittsburgh Steelers,28.0,20.0,428.0,0.0,406.0,2.0

In [3]:
NFL_df.columns

Index(['season', 'Week', 'Day', 'Date', 'Var.5', 'Winner/tie', 'Var.7',
       'Loser/tie', 'PtsW', 'PtsL', 'YdsW', 'TOW', 'YdsL', 'TOL'],
      dtype='object')

In [4]:
#EXTRACT "Team, Opposition, W/L, Runs and O-Runs"
reduced_NFL = NFL_df.loc[:, [ "season","Week", "Winner/tie","Var.7","Loser/tie","PtsW", "PtsL"]]
reduced_NFL.head(15)

    season Week           Winner/tie Var.7            Loser/tie  PtsW  PtsL
0     1960    1  St. Louis Cardinals     @     Los Angeles Rams  43.0  21.0
1     1960    1  Pittsburgh Steelers     @       Dallas Cowboys  35.0  28.0
2     1960    1        Chicago Bears     @    Green Bay Packers  17.0  14.0
3     1960    1      Baltimore Colts   NaN  Washington Redskins  20.0   0.0
4     1960    1      New York Giants     @  San Francisco 49ers  21.0  19.0
5     1960    1     Cleveland Browns     @  Philadelphia Eagles  41.0  24.0
6     1960    2  Philadelphia Eagles     @       Dallas Cowboys  27.0  25.0
7     1960    2    Green Bay Packers   NaN        Detroit Lions  28.0   9.0
8     1960    2  San Francisco 49ers   NaN     Los Angeles Rams  13.0   9.0
9     1960    2     Cleveland Browns   NaN  Pittsburgh Steelers  28.0  20.0
10    1960    2      New York Giants     @  St. Louis Cardinals  35.0  14.0
11    1960    2      Baltimore Colts   NaN        Chicago Bears  42.0   7.0
12    1960    3  San Francisco 49ers     @        Detroit Lions  14.0  10.0
13    1960    3        Chicago Bears   NaN     Los Angeles Rams  34.0  27.0
14    1960    3      New York Giants     @  Pittsburgh Steelers  19.0  17.0

In [5]:
reduced_NFL.dtypes

season          int64
Week           object
Winner/tie     object
Var.7          object
Loser/tie      object
PtsW          float64
PtsL          float64
dtype: object

In [6]:
reduced_NFL['Week'] = reduced_NFL.Week.astype(str)

In [7]:
reduced_NFL.dtypes

season          int64
Week           object
Winner/tie     object
Var.7          object
Loser/tie      object
PtsW          float64
PtsL          float64
dtype: object

In [36]:
reduced_nfl = reduced_NFL[~reduced_NFL['Week'].isin(["WildCard","Division","ConfChamp","SuperBowl","nan"])]

In [37]:
reduced_nfl.rename(columns={'Winner/tie': "Winner", 'Var.7': "HomeOrAway"}, inplace =True)
reduced_nfl.head()

C:\Users\cbucc\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

,season,Week,Winner,HomeOrAway,Loser/tie,PtsW,PtsL
0,1960,1,St. Louis Cardinals,1,Los Angeles Rams,43.0,21.0
1,1960,1,Pittsburgh Steelers,1,Dallas Cowboys,35.0,28.0
2,1960,1,Chicago Bears,1,Green Bay Packers,17.0,14.0
3,1960,1,Baltimore Colts,NaN,Washington Redskins,20.0,0.0
4,1960,1,New York Giants,1,San Francisco 49ers,21.0,19.0

In [38]:
reduced_NFL["Var.7"]= reduced_NFL["Var.7"].str.replace("@",'1', regex=True)
reduced_nfl.head()

,season,Week,Winner,HomeOrAway,Loser/tie,PtsW,PtsL
0,1960,1,St. Louis Cardinals,1,Los Angeles Rams,43.0,21.0
1,1960,1,Pittsburgh Steelers,1,Dallas Cowboys,35.0,28.0
2,1960,1,Chicago Bears,1,Green Bay Packers,17.0,14.0
3,1960,1,Baltimore Colts,NaN,Washington Redskins,20.0,0.0
4,1960,1,New York Giants,1,San Francisco 49ers,21.0,19.0

In [39]:
# 0 means home, 1 means away
reduced_nfl= reduced_nfl.fillna(0)
# reduced_NFL["Var.7"]= reduced_NFL["Var.7"].astype(int)
reduced_nfl.head(10)

,season,Week,Winner,HomeOrAway,Loser/tie,PtsW,PtsL
0,1960,1,St. Louis Cardinals,1,Los Angeles Rams,43.0,21.0
1,1960,1,Pittsburgh Steelers,1,Dallas Cowboys,35.0,28.0
2,1960,1,Chicago Bears,1,Green Bay Packers,17.0,14.0
3,1960,1,Baltimore Colts,0,Washington Redskins,20.0,0.0
4,1960,1,New York Giants,1,San Francisco 49ers,21.0,19.0
5,1960,1,Cleveland Browns,1,Philadelphia Eagles,41.0,24.0
6,1960,2,Philadelphia Eagles,1,Dallas Cowboys,27.0,25.0
7,1960,2,Green Bay Packers,0,Detroit Lions,28.0,9.0
8,1960,2,San Francisco 49ers,0,Los Angeles Rams,13.0,9.0
9,1960,2,Cleveland Browns,0,Pittsburgh Steelers,28.0,20.0

In [40]:
reduced_nfl['score_diff'] = reduced_nfl['PtsW'] - reduced_nfl['PtsL']
reduced_nfl.head()

,season,Week,Winner,HomeOrAway,Loser/tie,PtsW,PtsL,score_diff
0,1960,1,St. Louis Cardinals,1,Los Angeles Rams,43.0,21.0,22.0
1,1960,1,Pittsburgh Steelers,1,Dallas Cowboys,35.0,28.0,7.0
2,1960,1,Chicago Bears,1,Green Bay Packers,17.0,14.0,3.0
3,1960,1,Baltimore Colts,0,Washington Redskins,20.0,0.0,20.0
4,1960,1,New York Giants,1,San Francisco 49ers,21.0,19.0,2.0

In [41]:
home_wins_df= pd.DataFrame()
for season in reduced_nfl['season'].unique().tolist():
    home_df2 = reduced_nfl.loc[(reduced_nfl['season']==season)\
                              &(reduced_nfl['HomeOrAway']==0),:].copy()
    
    home_wins2 = home_df2.loc[:,'Winner'].values.tolist()
    home_wins_df[season] = pd.Series(dict(Counter(home_wins2)))
home_wins_df.fillna(0,inplace=True)
home_wins_df

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
Baltimore Colts,4,5,3.0,4,7,5,5,6,6,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Green Bay Packers,4,7,7.0,6,4,7,6,6,2,5,...,3.0,3.0,7.0,4.0,6.0,7.0,8.0,7.0,4.0,8.0
San Francisco 49ers,3,6,1.0,2,3,5,5,3,4,3,...,3.0,4.0,3.0,4.0,6.0,5.0,7.0,7.0,6.0,4.0
Cleveland Browns,4,4,4.0,5,6,5,5,6,5,5,...,4.0,2.0,7.0,1.0,3.0,3.0,3.0,4.0,3.0,4.0
Chicago Bears,4,5,4.0,7,2,5,4,3,2,1,...,7.0,6.0,4.0,6.0,5.0,5.0,5.0,5.0,5.0,2.0
Washington Redskins,2,1,3.0,1,4,3,4,3,3,5,...,6.0,3.0,5.0,4.0,3.0,2.0,2.0,5.0,2.0,3.0
Philadelphia Eagles,6,5,2.0,1,3,2,5,5,1,2,...,4.0,5.0,3.0,6.0,6.0,4.0,3.0,2.0,4.0,6.0
Pittsburgh Steelers,4,4,4.0,7,2,1,4,1,1,1,...,5.0,5.0,7.0,6.0,6.0,5.0,7.0,5.0,5.0,6.0
St. Louis Cardinals,4,3,2.0,3,4,2,5,3,4,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Detroit Lions,5,2,7.0,3,3,3,3,3,1,5,...,3.0,2.0,5.0,0.0,2.0,4.0,5.0,2.0,4.0,7.0
Los Angeles Rams,3,4,0.0,3,5,3,5,5,5,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
New York Giants,2,5,6.0,5,2,3,1,5,3,5,...,7.0,3.0,3.0,7.0,4.0,5.0,4.0,6.0,4.0,3.0

In [42]:
home_percent_wins=home_wins_df.div(8)
home_percent_wins.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
Baltimore Colts,0.500,0.625,0.375,0.500,0.875,0.625,0.625,0.750,0.750,0.500,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
Green Bay Packers,0.500,0.875,0.875,0.750,0.500,0.875,0.750,0.750,0.250,0.625,...,0.375,0.375,0.875,0.500,0.750,0.875,1.000,0.875,0.500,1.00
San Francisco 49ers,0.375,0.750,0.125,0.250,0.375,0.625,0.625,0.375,0.500,0.375,...,0.375,0.500,0.375,0.500,0.750,0.625,0.875,0.875,0.750,0.50
Cleveland Browns,0.500,0.500,0.500,0.625,0.750,0.625,0.625,0.750,0.625,0.625,...,0.500,0.250,0.875,0.125,0.375,0.375,0.375,0.500,0.375,0.50
Chicago Bears,0.500,0.625,0.500,0.875,0.250,0.625,0.500,0.375,0.250,0.125,...,0.875,0.750,0.500,0.750,0.625,0.625,0.625,0.625,0.625,0.25

In [43]:

away_wins_df= pd.DataFrame()
for season in reduced_nfl['season'].unique().tolist():
    away_df2 = reduced_nfl.loc[(reduced_nfl['season']==season)\
                              &(reduced_nfl['HomeOrAway']=='1'),:].copy()
#     print(away_df2.head())
    away_wins2 = away_df2.loc[:,'Winner'].values.tolist()
    away_wins_df[season] = pd.Series(dict(Counter(away_wins2)))
away_wins_df.fillna(0,inplace=True)
away_wins_df

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
St. Louis Cardinals,3,4.0,2,6.0,6,3,3.0,3,5,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Pittsburgh Steelers,1,2.0,5,3.0,3,1,2.0,4,2,0.0,...,6.0,3.0,3.0,6.0,3.0,7.0,5.0,3.0,3.0,5.0
Chicago Bears,1,3.0,5,5.0,3,4,1.0,4,5,0.0,...,4.0,7.0,3.0,3.0,2.0,6.0,3.0,5.0,3.0,3.0
New York Giants,5,6.0,6,6.0,2,4,0.0,2,4,1.0,...,4.0,5.0,7.0,5.0,4.0,5.0,5.0,3.0,3.0,3.0
Cleveland Browns,4,4.0,3,5.0,5,6,4.0,3,5,5.0,...,2.0,2.0,3.0,3.0,2.0,2.0,1.0,1.0,1.0,3.0
Philadelphia Eagles,5,5.0,2,1.0,3,3,4.0,1,1,2.0,...,2.0,5.0,5.0,4.0,5.0,6.0,5.0,2.0,6.0,4.0
San Francisco 49ers,4,2.0,5,0.0,1,3,3.0,4,4,2.0,...,1.0,3.0,2.0,3.0,2.0,1.0,6.0,5.0,6.0,4.0
Washington Redskins,1,1.0,4,2.0,2,3,3.0,5,2,4.0,...,4.0,2.0,4.0,4.0,1.0,4.0,3.0,5.0,1.0,1.0
Green Bay Packers,4,5.0,7,6.0,4,4,7.0,5,5,3.0,...,1.0,5.0,6.0,2.0,5.0,3.0,7.0,4.0,4.0,4.0
Baltimore Colts,2,3.0,4,4.0,5,5,4.0,5,8,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Detroit Lions,2,6.0,4,2.0,4,4,2.0,2,3,5.0,...,2.0,1.0,2.0,0.0,0.0,2.0,5.0,2.0,3.0,4.0
Los Angeles Rams,2,0.0,2,2.0,2,1,3.0,7,5,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
away_percent_wins = away_wins_df.div(8)
away_percent_wins.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
St. Louis Cardinals,0.375,0.500,0.250,0.750,0.750,0.375,0.375,0.375,0.625,0.250,...,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Pittsburgh Steelers,0.125,0.250,0.625,0.375,0.375,0.125,0.250,0.500,0.250,0.000,...,0.75,0.375,0.375,0.750,0.375,0.875,0.625,0.375,0.375,0.625
Chicago Bears,0.125,0.375,0.625,0.625,0.375,0.500,0.125,0.500,0.625,0.000,...,0.50,0.875,0.375,0.375,0.250,0.750,0.375,0.625,0.375,0.375
New York Giants,0.625,0.750,0.750,0.750,0.250,0.500,0.000,0.250,0.500,0.125,...,0.50,0.625,0.875,0.625,0.500,0.625,0.625,0.375,0.375,0.375
Cleveland Browns,0.500,0.500,0.375,0.625,0.625,0.750,0.500,0.375,0.625,0.625,...,0.25,0.250,0.375,0.375,0.250,0.250,0.125,0.125,0.125,0.375

In [17]:
# home_wins_df.to_csv(index=True)
# home_wins_df.to_excel("NFL_home_Wins.xlsx")

In [18]:
# away_wins_df.to_csv(index=True)
# away_wins_df.to_excel("NFL_away_Wins.xlsx")

In [19]:
home_percent_wins.to_csv(index=True)
home_percent_wins.to_excel("NFLHome_percent_Wins.xlsx")

In [20]:
away_percent_wins.to_csv(index=True)
away_percent_wins.to_excel("NFLAway_percent_Wins.xlsx")

In [46]:
total_wins= (away_percent_wins + home_percent_wins )/2
total_wins.head()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
Baltimore Colts,0.3750,0.50,0.4375,0.5000,0.7500,0.6250,0.5625,0.6875,0.8750,0.5000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Chicago Bears,0.3125,0.50,0.5625,0.7500,0.3125,0.5625,0.3125,0.4375,0.4375,0.0625,...,0.6875,0.8125,0.4375,0.5625,0.4375,0.6875,0.5000,0.6250,0.5000,0.3125
Cleveland Browns,0.5000,0.50,0.4375,0.6250,0.6875,0.6875,0.5625,0.5625,0.6250,0.6250,...,0.3750,0.2500,0.6250,0.2500,0.3125,0.3125,0.2500,0.3125,0.2500,0.4375
Detroit Lions,0.4375,0.50,0.6875,0.3125,0.4375,0.4375,0.3125,0.3125,0.2500,0.6250,...,0.3125,0.1875,0.4375,0.0000,0.1250,0.3750,0.6250,0.2500,0.4375,0.6875
Green Bay Packers,0.5000,0.75,0.8750,0.7500,0.5000,0.6875,0.8125,0.6875,0.4375,0.5000,...,0.2500,0.5000,0.8125,0.3750,0.6875,0.6250,0.9375,0.6875,0.5000,0.7500

In [47]:
total_wins.dropna()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
Baltimore Colts,0.3750,0.5000,0.4375,0.5000,0.7500,0.6250,0.5625,0.6875,0.8750,0.5000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Chicago Bears,0.3125,0.5000,0.5625,0.7500,0.3125,0.5625,0.3125,0.4375,0.4375,0.0625,...,0.6875,0.8125,0.4375,0.5625,0.4375,0.6875,0.5000,0.6250,0.5000,0.3125
Cleveland Browns,0.5000,0.5000,0.4375,0.6250,0.6875,0.6875,0.5625,0.5625,0.6250,0.6250,...,0.3750,0.2500,0.6250,0.2500,0.3125,0.3125,0.2500,0.3125,0.2500,0.4375
Detroit Lions,0.4375,0.5000,0.6875,0.3125,0.4375,0.4375,0.3125,0.3125,0.2500,0.6250,...,0.3125,0.1875,0.4375,0.0000,0.1250,0.3750,0.6250,0.2500,0.4375,0.6875
Green Bay Packers,0.5000,0.7500,0.8750,0.7500,0.5000,0.6875,0.8125,0.6875,0.4375,0.5000,...,0.2500,0.5000,0.8125,0.3750,0.6875,0.6250,0.9375,0.6875,0.5000,0.7500
Los Angeles Rams,0.3125,0.2500,0.1250,0.3125,0.4375,0.2500,0.5000,0.7500,0.6250,0.6875,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
New York Giants,0.4375,0.6875,0.7500,0.6875,0.2500,0.4375,0.0625,0.4375,0.4375,0.3750,...,0.6875,0.5000,0.6250,0.7500,0.5000,0.6250,0.5625,0.5625,0.4375,0.3750
Philadelphia Eagles,0.6875,0.6250,0.2500,0.1250,0.3750,0.3125,0.5625,0.3750,0.1250,0.2500,...,0.3750,0.6250,0.5000,0.6250,0.6875,0.6250,0.5000,0.2500,0.6250,0.6250
Pittsburgh Steelers,0.3125,0.3750,0.5625,0.6250,0.3125,0.1250,0.3750,0.3125,0.1875,0.0625,...,0.6875,0.5000,0.6250,0.7500,0.5625,0.7500,0.7500,0.5000,0.5000,0.6875
San Francisco 49ers,0.4375,0.5000,0.3750,0.1250,0.2500,0.5000,0.5000,0.4375,0.5000,0.3125,...,0.2500,0.4375,0.3125,0.4375,0.5000,0.3750,0.8125,0.7500,0.7500,0.5000
St. Louis Cardinals,0.4375,0.4375,0.2500,0.5625,0.6250,0.3125,0.5000,0.3750,0.5625,0.3125,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Washington Redskins,0.1875,0.1250,0.4375,0.1875,0.3750,0.3750,0.4375,0.5000,0.3125,0.5625,...,0.6250,0.3125,0.5625,0.5000,0.2500,0.3750,0.3125,0.6250,0.1875,0.2500

In [48]:
total_wins.to_csv(index=True)
total_wins.to_excel("NFL_totalPercentWins.xlsx")